-- Example: Even distribution of user data
CREATE TABLE users (
user_id BIGINT,
email VARCHAR(255),
created_at TIMESTAMP
) PARTITION BY HASH (user_id);
CREATE TABLE users_p0 PARTITION OF users FOR VALUES WITH
(MODULUS 4, REMAINDER 0);
CREATE TABLE users_p1 PARTITION OF users FOR VALUES WITH
(MODULUS 4, REMAINDER 1);
CREATE TABLE users_p2 PARTITION OF users FOR VALUES WITH
(MODULUS 4, REMAINDER 2);
CREATE TABLE users_p3 PARTITION OF users FOR VALUES WITH
(MODULUS 4, REMAINDER 3);
